- name: Update and Install Required Packages
  hosts: all
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        autoremove: yes

    - name: install required system packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - net-tools
        - apt-transport-https
        - ca-certificates
        - curl
        - lsb-release
        - gnupg
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
        - vim
        - build-essential
        - gdb

    - name: Install Python
      apt:
        name: python3
        state: present

- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: add docker gpg apt apt_key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: install docker
      apt:
        name:
          [
            "docker-ce",
            "docker-ce-cli",
            "containerd.io",
            "docker-buildx-plugin",
            "docker-compose-plugin",
          ]
        update_cache: yes


